<?php

namespace Tests\Unit\Controllers;

use Event;
use App\Events\NotifyAdmin;
use App\Http\Controllers\InventoryController;
use App\Inventory;
use Illuminate\Http\Request;
use Mockery;

class InventoryControllerTest extends \Tests\TestCase
{
    protected $inventoryController;
    protected $request;
    protected $inventory;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->inventoryController = Mockery::mock(InventoryController::class)->makePartial();
        $this->request = Mockery::mock(Request::class)->makePartial();
        $this->inventory = Mockery::mock(Inventory::class)->makePartial();
    }

    public function makePropertyAccessible(&$object, $property, $value, $class)
    {
        $reflection = new \ReflectionClass($class);
        $property = $reflection->getProperty($property);
        $property->setAccessible(true);
        $property->setValue($object, $value);
    }

    public function testIfCreateIsWorkingWhenDetailsAreCorrect()
    {
        Event::fake();
        $this->request->shouldReceive('all')->andReturn(['name' => 'desk','price' => 2]);
        $this->inventory->shouldReceive('create')->andReturn(true);
        $this->makePropertyAccessible($this->inventoryController, 'inventory', $this->inventory, InventoryController::class);
        $this->makePropertyAccessible($this->inventoryController, 'request', $this->request, InventoryController::class);
        $reponse = json_decode($this->inventoryController->create()->getContent(), true);
        Event::assertDispatched(NotifyAdmin::class);
        $this->assertSame($reponse, ['status' => 'success','message' => 'item has been successfully added']);
    }

    public function testIfCreateIsWorkingWhenDetailsAreIncorrect()
    {
        Event::fake();
        $this->request->shouldReceive('all')->andReturn(['name' => 'desk']);
        $this->inventory->shouldReceive('create')->andReturn(true);
        $this->makePropertyAccessible($this->inventoryController, 'inventory', $this->inventory, InventoryController::class);
        $this->makePropertyAccessible($this->inventoryController, 'request', $this->request, InventoryController::class);
        $reponse = json_decode($this->inventoryController->create()->getContent(), true);
        Event::assertNotDispatched(NotifyAdmin::class);
        $this->assertSame($reponse, ['status' => 'error','message' => 'item name or price is missing']);
    }


}