version: '3'
services:
  unittest.pv:
    container_name: unittest.pv
    image: pagevamp/nginx-php7-fpm:7.2
    restart: always
    env_file: .env
    environment:
      - VIRTUAL_HOST=unittest.pv
    volumes:
      - CacheVolume:/var/www/public/sites
      - ./:/var/www
      - ./docker/sites/default.conf:/etc/nginx/sites-enabled/default
    networks:
      - pagevamp

networks:
  pagevamp:
    external: true

volumes:
  CacheVolume:
    external: true
